
# redirect jebatderhaka.com to www.jebatderhaka.com
# 1. Redirect HTTP (port 80) to HTTPS (port 443), and non-www to www
server {
    listen 80;
    server_name jebatderhaka.com www.jebatderhaka.com;

    return 301 https://www.jebatderhaka.com$request_uri;
}

# 2. Redirect non-www HTTPS to www HTTPS
server {
    listen 443 ssl;
    server_name jebatderhaka.com;


    ssl_certificate /etc/nginx/certs/FullChain.pem;
    ssl_certificate_key /etc/nginx/keys/private.key;

    return 301 https://www.jebatderhaka.com$request_uri;
}


server {
    server_name www.jebatderhaka.com;

    root /var/www/jebatderhaka.com/build;

    # frontend
    location / {
        try_files $uri $uri/ /index.html;
    }


    # storage stored in Laravel
    location /storage {
           alias /var/www/jebatderhaka.com/api/storage/app/public/;
           index index.html;
           autoindex off;  # Optional, enables directory listing if needed
    }

    # laravel API server
    location /api {
         client_max_body_size 256M;
         alias /var/www/jebatderhaka.com/api/public;
         index index.php;
         try_files $uri $uri/ @laravelapi;

         # pass PHP scripts to FastCGI server
         location ~ \.php$ {
             include snippets/fastcgi-php.conf;
             #fastcgi_pass unix:/run/php/php8.1-fpm.sock;
             fastcgi_pass unix:/run/php/php8.2-fpm.sock;
             include fastcgi_params;
             fastcgi_read_timeout 600;
             fastcgi_param SCRIPT_FILENAME $request_filename;
             fastcgi_param SCRIPT_NAME /api$fastcgi_script_name;
      }
    }

    # laravel API rewrite
    location @laravelapi {
        rewrite /api/(.*)?$ /api/index.php?$is_args$args last;
    }

    # SSL
    listen 443 ssl; # managed by StreamDotMy.com
    server_name  jebatderhaka.com;
    ssl_certificate /etc/nginx/jebatderhaka.com/certs/FullChain.pem;
    ssl_certificate_key /etc/nginx/jebatderhaka.com/keys/private.key;

}

# redirect http to https
server {
    if ($host = www.jebatderhaka.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name www.jebatderhaka.com;
    return 404; # managed by Certbot
}
