

worker_processes  1;

events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  localhost;


        location / {
            root   html;
            index  index.html index.htm;
        }
        
        

    }


    # HTTPS server
    #
    server {
       listen       443 ssl;
       server_name  rtm.gov.my;

       ssl_certificate      c:\\nginx\\conf\\certs\\gabung.pem;
       ssl_certificate_key  c:\\nginx\\conf\\key\\wildcard_rtm_gov_my.key;

       ssl_session_cache    shared:SSL:1m;
       ssl_session_timeout  5m;

       ssl_ciphers  HIGH:!aNULL:!MD5;
       ssl_prefer_server_ciphers  on;
       ssl_protocols TLSv1.2 TLSv1.3;
    

       location / {
           root   html;
           index  index.html index.htm;
       }
    }

}
