server {
    listen 8080;
    server_name localhost;

    # Define access logs
    access_log /var/log/nginx/localhost_access.log;
    error_log /var/log/nginx/localhost_error.log;


    root /var/www/localhost/boilerplate/api/public;


    location /api {
        client_max_body_size 256M;
        alias /var/www/localhost/boilerplate/api/public;
        index index.php
        try_files $uri $uri/ @laravelapi; 

        location ~ \.php$ {
            include snippets/fastcgi-php.conf;
            fastcgi_pass unix:/run/php/php8.2-fpm.sock;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $request_filename;
            fastcgi_param SCRIPT_NAME /api$fastcgi_script_name; // makes laravel thinks in /api
       }
    }

    location @laravelapi {
        rewrite /api/(.*)?$ /api/index.php?$is_args$args last;
    }

    location 

}